### ISSUE TITLE
train.py failure

### ISSUE THREAD

**Issue by imitn** [flyingpot/pytorch_deephash#11]
from net import AlexNetPlusLatent

**Comment by imitn** [comment]
Hi @flyingpot,
I'm sorry to bother you. 
When I follow your guide in readme to execute "python train.py", it failures because of no package "net".
Can you tell me how to install the package ,  because I can not get the relevant information with it using google.

the log as follow.

(py36) wjd-ubuntu@ubuntu:~/develop/git/pytorch_deephash$ python3 train.py 
Downloading: "https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth" to /home/wjd-ubuntu/.torch/models/alexnet-owt-4df8aa71.pth
Traceback (most recent call last):
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from net import AlexNetPlusLatent
  File "/home/wjd-ubuntu/develop/git/pytorch_deephash/net.py", line 4, in <module>
    alexnet_model = models.alexnet(pretrained=True)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 58, in alexnet
    model.load_state_dict(model_zoo.load_url(model_urls['alexnet']))
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 65, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 70, in _download_url_to_file
    u = urlopen(url)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/wjd-ubuntu/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
(py36) wjd-ubuntu@ubuntu:~/develop/git/pytorch_deephash$ python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

**Comment by spoonnotfound** [comment]
Hi, your problem is not what you describe. The net module is defined in the file named net.py. And the error happens because of the network problem. Sometimes you cannot download the network model file successfully. You can download it by yourself, and the url is here https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth. You need to put the file in this directory /home/wjd-ubuntu/.torch/models/alexnet-owt-4df8aa71.pth
You can find the information from the error log.

**Comment by imitn** [comment]
Hi @flyingpot,
I am a  freshman， you are right，thank you very much.
