### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by world2025** [flyingpot/pytorch_deephash#12]
你好，我在run train.py的时候出现一个错误，poch: 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\tk2018\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\tk2018\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\tk2018\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\bi ye she ji 2020\pytorch_deephash-master\train.py", line 124, in <module>
    train(epoch)
  File "D:\bi ye she ji 2020\pytorch_deephash-master\train.py", line 71, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):
  File "D:\tk2018\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "D:\tk2018\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "D:\tk2018\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\tk2018\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\tk2018\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "D:\tk2018\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "D:\tk2018\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "D:/bi ye she ji 2020/pytorch_deephash-master/train.py", line 124, in <module>
    train(epoch)
  File "D:/bi ye she ji 2020/pytorch_deephash-master/train.py", line 71, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):
  File "D:\tk2018\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "D:\tk2018\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "D:\tk2018\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\tk2018\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\tk2018\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "D:\tk2018\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\tk2018\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
请问这个问题如何解决，谢谢

**Comment by spoonnotfound** [comment]
应该是Windows下多线程的问题，由于我在Linux环境下运行，所以没有遇到这个问题。根据这个[链接](https://discuss.pytorch.org/t/brokenpipeerror-errno-32-broken-pipe-when-i-run-cifar10-tutorial-py/6224)，你把两个num_workers参数改成0应该可以解决问题。

**Comment by world2025** [comment]
哦哦，是多线程问题，谢谢！
